#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_check:
    path: /login_check
    methods: [POST]

new_user:
    path: /users
    controller: App\Controller\UserController::newUser
    methods: [POST]
